# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 01:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(default='ATIVO', max_length=100)),
                ('codigo', models.CharField(max_length=200, unique=True)),
                ('modalidade_negocio', models.CharField(choices=[('VENDA', 'VENDA'), ('TROCA', 'TROCA')], default='TROCA', max_length=2)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('categoria', models.CharField(default='', max_length=255)),
                ('ano_publicacao', models.IntegerField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date(2017, 9, 10))),
                ('estante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.Estante')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('ES', 'ES'), ('MG', 'MG'), ('RJ', 'RJ'), ('SP', 'SP'), ('AL', 'AL'), ('BA', 'BA'), ('CE', 'CE'), ('MA', 'MA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('RN', 'RN'), ('SE', 'SE'), ('DF', 'DF'), ('GO', 'GO'), ('MT', 'MT'), ('MS', 'MS'), ('AC', 'AC'), ('AP', 'AP'), ('AM', 'AM'), ('PA', 'PA'), ('RO', 'RO'), ('RR', 'RR'), ('TO', 'TO'), ('PR', 'PR'), ('SC', 'SC'), ('RS', 'RS')], max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='operacao',
            name='usuario_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.Usuario'),
        ),
        migrations.AddField(
            model_name='livro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.Usuario'),
        ),
        migrations.AddField(
            model_name='estante',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estante', to='livros.Livro'),
        ),
        migrations.AddField(
            model_name='autor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.Usuario'),
        ),
    ]
