# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 02:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_auto_20170910_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 9, 11, 2, 5, 55, 729559, tzinfo=utc)),
        ),
    ]
