# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 21:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_auto_20170910_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='data',
            field=models.DateField(default=datetime.datetime(2017, 9, 20, 21, 58, 54, 178859, tzinfo=utc)),
        ),
    ]
